from centos:centos6

run yum -y install http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm && \
    yum -y update && \
    yum -y install rpm-build make gcc glibc-devel gcc-c++ rsync && \
    yum -y clean all
run mkdir /app
copy . /app/
workdir /app
run export V=pacifica-upload-status-0.99.6 && \
    ln -s . $V && \
    tar --exclude=$V/$V --exclude=$V/$V.tar.gz -czf $V.tar.gz $V/* && \
    rpmbuild -ba --define '_sourcedir '$PWD pacifica-upload-status.spec
