from nginx

COPY ./auth/htpasswd /etc/nginx/.htpasswd
COPY ./auth/proxy.template /etc/nginx/conf.d/mysite.template
COPY ./auth/proxyentrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
